### ISSUE TITLE
Create basic algorithm for product recommendation

### ISSUE THREAD

**Issue by SimonFlensted** [HHIED/Datamining#15]
Develop basic code skeleton and algorithm for product recommendation, involving behavior data.
This includes the following processes:
- A visitorUID is received
- VisitorUID is used to gather behavior data
- Behavior data is used to gather products for recommendation
- Most relevant products are selected
- List of productUIDs is returned

**Comment by corfixen** [comment]
It looks fine for iteration 3. Remember to do the units test and integrations continuously. It is a good idea to do continues integration using a build-sever.
